on:
  push:
    branches: [main, master, test, develop]
  pull_request:
    branches: [main, master, develop]

name: databaseconnector-redshift-test

jobs:
  Postgres-test:
    # if: github.repository == 'darwin-eu/CDMConnector'
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-eu-dev/examplestudy-base:latest
      env:
          CDM5_REDSHIFT_SERVER:          ${{ secrets.CDM5_REDSHIFT_SERVER }}
          CDM5_REDSHIFT_USER:            ${{ secrets.CDM5_REDSHIFT_USER }}
          CDM5_REDSHIFT_PASSWORD:        ${{ secrets.CDM5_REDSHIFT_PASSWORD }}
          CDM5_REDSHIFT_PORT:            ${{ secrets.CDM5_REDSHIFT_PORT }}
          CDM5_REDSHIFT_CDM_SCHEMA:      ${{ secrets.CDM5_REDSHIFT_CDM_SCHEMA }}
          CDM5_REDSHIFT_SCRATCH_SCHEMA:  ${{ secrets.CDM5_REDSHIFT_SCRATCH_SCHEMA }}
          GITHUB_PAT:                    ${{ secrets.GITHUB_TOKEN }}

    name: Redshift test (DatabaseConnector driver)

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          install.packages("gert", repos = "https://cloud.r-project.org/")
          install.packages("usethis", repos = "https://cloud.r-project.org/")
          install.packages("devtools", repos = "https://cloud.r-project.org/")
          install.packages("remotes", repos = "https://cloud.r-project.org/")
          install.packages("palmerpenguins", repos = "https://cloud.r-project.org/")
          install.packages("omopgenerics", repos = "https://cloud.r-project.org/")
          remotes::install_github("tidyverse/dbplyr")
          remotes::install_github("OHDSI/DatabaseConnector@version_7")
          CDMConnector::download_eunomia_data()
          print(paste("eunomiaIsAvailable():", CDMConnector::eunomiaIsAvailable()))
        shell: Rscript {0}

      - name: Run tests on redshift with DatabaseConnector JDBC driver
        run: R -e 'install.packages("devtools", repos = "https://cloud.r-project.org/"); devtools::install(); withr::with_envvar(new = c("CI_TEST_DB" = "redshift", "TEST_USING_DATABASE_CONNECTOR" = "TRUE"), testthat::test_local())'


