on:
  push:
    branches: [main, master, test, develop]
  pull_request:
    branches: [main, master, develop]

name: databaseconnector-postgres-test

jobs:
  Postgres-test:
    # if: github.repository == 'darwin-eu/CDMConnector'
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-eu-dev/examplestudy-base:latest
      env:
        CDM5_POSTGRESQL_USER:           ${{ secrets.CDM5_POSTGRESQL_USER }}
        CDM5_POSTGRESQL_PORT:           ${{ secrets.CDM5_POSTGRESQL_PORT }}
        CDM5_POSTGRESQL_PASSWORD:       ${{ secrets.CDM5_POSTGRESQL_PASSWORD }}
        CDM5_POSTGRESQL_SERVER:         ${{ secrets.CDM5_POSTGRESQL_SERVER }}
        CDM5_POSTGRESQL_HOST:           ${{ secrets.CDM5_POSTGRESQL_HOST }}
        CDM5_POSTGRESQL_DBNAME:         ${{ secrets.CDM5_POSTGRESQL_DBNAME }}
        CDM5_POSTGRESQL_CDM_SCHEMA:     ${{ secrets.CDM5_POSTGRESQL_CDM_SCHEMA }}
        CDM5_POSTGRESQL_OHDSI_SCHEMA:   ${{ secrets.CDM5_POSTGRESQL_OHDSI_SCHEMA }}
        CDM5_POSTGRESQL_SCRATCH_SCHEMA: ${{ secrets.CDM5_POSTGRESQL_SCRATCH_SCHEMA }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    name: Postgres test (DatabaseConnector driver)

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Run a simple shell command
        run: ls

      - name: Run one R command
        run: R -e "getwd()"

      - name: Install Packages
        run: |
          print(getwd())
          print(list.files())
          install.packages("gert", repos = "https://cloud.r-project.org/")
          install.packages("usethis", repos = "https://cloud.r-project.org/")
          install.packages("devtools", repos = "https://cloud.r-project.org/")
          install.packages("remotes", repos = "https://cloud.r-project.org/")
          install.packages("omopgenerics", repos = "https://cloud.r-project.org/")
          install.packages("palmerpenguins", repos = "https://cloud.r-project.org/")
          remotes::install_github("tidyverse/dbplyr")
          CDMConnector::download_eunomia_data()
          print(paste("eunomiaIsAvailable():", CDMConnector::eunomiaIsAvailable()))
        shell: Rscript {0}

      - name: Run tests on postgres with DatabaseConnector JDBC driver
        run: R -e 'devtools::install(); withr::with_envvar(new = c("CI_TEST_DB" = "postgres", "TEST_USING_DATABASE_CONNECTOR" = "TRUE"), testthat::test_local())'


