on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: redshift-test

jobs:
  Postgres-test:
    if: github.repository == 'darwin-eu/CDMConnector'
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-base:v0.1
      env:
        CDM5_REDSHIFT_USER:           ${{ secrets.CDM5_REDSHIFT_USER }}
        CDM5_REDSHIFT_PORT:           ${{ secrets.CDM5_REDSHIFT_PORT }}
        CDM5_REDSHIFT_PASSWORD:       ${{ secrets.CDM5_REDSHIFT_PASSWORD }}
        CDM5_REDSHIFT_SERVER:         ${{ secrets.CDM5_REDSHIFT_SERVER }}
        CDM5_REDSHIFT_HOST:           ${{ secrets.CDM5_REDSHIFT_HOST }}
        CDM5_REDSHIFT_DBNAME:         ${{ secrets.CDM5_REDSHIFT_DBNAME }}
        CDM5_REDSHIFT_CDM_SCHEMA:     ${{ secrets.CDM5_REDSHIFT_CDM_SCHEMA }}
        CDM5_REDSHIFT_OHDSI_SCHEMA:   ${{ secrets.CDM5_REDSHIFT_OHDSI_SCHEMA }}
        CDM5_REDSHIFT_SCRATCH_SCHEMA: ${{ secrets.CDM5_REDSHIFT_SCRATCH_SCHEMA }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    name: Redshift test (RPostgres driver)

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Run tests on Redshift with RPostgres driver
        run: R -e 'withr::with_envvar(new = c("CI_TEST_DB" = "redshift"), testthat::test_local())'


