on:
  push:
    branches: [main, master, test, develop]
  pull_request:
    branches: [main, master, develop]

name: snowflake-odbc-test

jobs:
  Postgres-test:
    # if: github.repository == 'darwin-eu/CDMConnector'
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-base:v0.3
      env:
        SNOWFLAKE_CONNECTION_STRING: ${{ secrets.SNOWFLAKE_CONNECTION_STRING }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_SERVER: ${{ secrets.SNOWFLAKE_SERVER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DRIVER: "/usr/lib/snowflake/odbc/lib/libSnowflake.so"
        SNOWFLAKE_CDM_SCHEMA: ${{ secrets.SNOWFLAKE_CDM_SCHEMA }}
        SNOWFLAKE_SCRATCH_SCHEMA: ${{ secrets.SNOWFLAKE_SCRATCH_SCHEMA }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        TESTTHAT_CPUS : 1

    name: Snowflake test (odbc driver)

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Install R packages
        run: |
          print(getwd())
          print(list.files())
          install.packages("devtools", repos = "https://cloud.r-project.org/")
          install.packages("remotes", repos = "https://cloud.r-project.org/")
          install.packages("omopgenerics", repos = "https://cloud.r-project.org/")
          install.packages("palmerpenguins", repos = "https://cloud.r-project.org/")
          remotes::install_github("tidyverse/dbplyr")
        shell: Rscript {0}

      - name: Run tests on Snowflake with odbc driver
        run: R -e 'devtools::install(); withr::with_envvar(new = c("CI_TEST_DB" = "snowflake", "TEST_USING_DATABASE_CONNECTOR" = "FALSE"), testthat::test_local())'


